const UTL_DATA_FLAG_CURRENTS = 0x10;
const UTL_DATA_FLAG_TEMPERATURES = 0x11;

const UTL_DATA_FLAG_CA_HEADER = 0x20;
const UTL_DATA_FLAG_CV_HEADER = 0x21;
const UTL_DATA_FLAG_DPV_HEADER = 0x22;

const UTL_DATA_FLAG_CA_COMMAND = 0x30;
const UTL_DATA_FLAG_CV_COMMAND = 0x31;
const UTL_DATA_FLAG_DPV_COMMAND = 0x32;

const UTL_DATA_FLAG_CORTISOL_HEADER = 0x40;
const UTL_DATA_FLAG_LACTATE_HEADER = 0x41;
const UTL_DATA_FLAG_H1N1_HEADER = 0x42;
