import 'package:utl_electrochemical_tester/controller/electrochemical_command_controller.dart';
import 'package:utl_electrochemical_tester/controller/electrochemical_dashboard_controller.dart';

class ControllerRegistry {
  ControllerRegistry._();
  static ElectrochemicalCommandController get electrochemicalCommandController;
  static ElectrochemicalLineChartController get electrochemicalLineChartController;
  static ElectrochemicalLineChartInfoController get electrochemicalLineChartInfoController;
  static ElectrochemicalLineChartSetterController get electrochemicalLineChartSetterController;
  static ElectrochemicalFeatureController get electrochemicalFeatureController;
}
